<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <RootNamespace>L2Cache.Tests.Integration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\L2Cache\L2Cache.csproj" />
    <ProjectReference Include="..\..\src\L2Cache.Serializers.Json\L2Cache.Serializers.Json.csproj" />
    <ProjectReference Include="..\..\src\L2Cache.Serializers.MemoryPack\L2Cache.Serializers.MemoryPack.csproj" />
    <ProjectReference Include="..\..\src\L2Cache.Telemetry\L2Cache.Telemetry.csproj" />
  </ItemGroup>

</Project>